namespace ExileCore.Shared.Enums
{
    /// <summary>
    /// Inventory identifiers as exposed by the reference distribution.
    /// </summary>
    public enum InventoryNameE
    {
        None = 0,
        MainInventory1 = 1,
        BodyArmour1 = 2,
        Weapon1 = 3,
        Offhand1 = 4,
        Helm1 = 5,
        Amulet1 = 6,
        Ring1 = 7,
        Ring2 = 8,
        Gloves1 = 9,
        Boots1 = 10,
        Belt1 = 11,
        Flask1 = 12,
        Cursor1 = 13,
        Map1 = 14,
        Weapon2 = 15,
        Offhand2 = 16,
        StrMasterCrafting = 17,
        StrDexMasterCrafting = 18,
        DexMasterCrafting = 19,
        DexIntMasterCrafting = 20,
        IntMasterCrafting = 21,
        StrIntMasterCrafting = 22,
        PVPMasterCrafting = 23,
        PassiveJewels1 = 24,
        AnimatedArmour1 = 25,
        GuildTag1 = 26,
        StashInventoryId = 27,
        DivinationCardTrade = 28,
        Darkshrine = 29,
        TalismanTrade = 30,
        Leaguestone1 = 31,
        BestiaryCrafting = 32,
        IncursionSacrifice = 33,
        BetrayalUnveiling = 34,
        ItemSynthesisInput = 35,
        ItemSynthesisOutput = 36,
        BlightCraftingInput = 37,
        BlightCraftingItem = 38,
        MetamorphosisGenomeInput = 39,
        AtlasUpgrades1 = 40,
        AtlasUpgradesStorage = 41,
        ExpeditionMapMission = 42,
        ExpeditionDeal1 = 43,
        HarvestCraftingItem = 44,
        HeistContractMission = 45,
        HeistNpcEquipment1 = 46,
        HeistNpcEquipment2 = 47,
        HeistNpcEquipment3 = 48,
        HeistNpcEquipment4 = 49,
        HeistNpcEquipment5 = 50,
        HeistNpcEquipment6 = 51,
        HeistNpcEquipment7 = 52,
        HeistNpcEquipment8 = 53,
        HeistNpcEquipment9 = 54,
        Trinket1 = 55,
        HeistBlueprintMission = 56,
        HeistStorage1 = 57,
        RitualSavedRewards1 = 58,
        DONOTUSE1 = 59,
        DONOTUSE2 = 60,
        DONOTUSE3 = 61,
        DONOTUSE4 = 62,
        RESERVED1 = 63,
        RESERVED2 = 64,
        RESERVED3 = 65,
        RESERVED4 = 66,
        UltimatumCraftingItem = 67,
        RESERVED5 = 68,
        RESERVED6 = 69,
        ExpeditionStorage1 = 70,
        HellscapeModificationInventory1 = 71,
        LabyrinthCraftingInput = 72,
        SentinelDroneInventory1 = 73,
        SentinelStorage1 = 74,
    }
}
