namespace ExileCore.Shared.Enums
{
    /// <summary>
    /// Copied from GGPK -> Inventories.dat file
    /// Possible improvement -> read it from the in memory dad file
    /// </summary>
    public enum InventorySlotE
    {
        MainInventory1,
        BodyArmour1,
        Weapon1,
        Offhand1,
        Helm1,
        Amulet1,
        Ring1,
        Ring2,
        Gloves1,
        Boots1,
        Belt1,
        Flask1,
        Cursor1,
        Map1,
        Weapon2,
        Offhand2,
        StrMasterCrafting,
        StrDexMasterCrafting,
        DexMasterCrafting,
        DexIntMasterCrafting,
        IntMasterCrafting,
        StrIntMasterCrafting,
        PVPMasterCrafting,
        PassiveJewels1,
        AnimatedArmour1,
        GuildTag1,
        StashInventoryId,
        DivinationCardTrade,
        Darkshrine,
        TalismanTrade,
        Leaguestone1,
        BestiaryCrafting,
        IncursionSacrifice,
        BetrayalUnveiling,
        ItemSynthesisInput,
        ItemSynthesisOutput,

        BlightCraftingInput = 36,
        BlightCraftingItem = 37,
        DONOTUSE5 = 38,
        AtlasUpgrades1 = 39,
        AtlasUpgradesStorage = 40,
        ExpeditionMapMission = 41,
        ExpeditionDeal1 = 42,
        HarvestCraftingItem = 43,
        HeistContractMission = 44,
        HeistNpcEquipment1 = 45,
        HeistNpcEquipment2 = 46,
        HeistNpcEquipment3 = 47,
        HeistNpcEquipment4 = 48,
        HeistNpcEquipment5 = 49,
        HeistNpcEquipment6 = 50,
        HeistNpcEquipment7 = 51,
        HeistNpcEquipment8 = 52,
        HeistNpcEquipment9 = 53,
        Trinket1 = 54,
        HeistBlueprintMission = 55,
        HeistStorage1 = 56,
        RitualSavedRewards1 = 57,
        DONOTUSE1 = 58,
        DONOTUSE2 = 59,
        DONOTUSE3 = 60,
        DONOTUSE4 = 61,
        MapDeviceStorage1 = 62,
        RESERVED2 = 63,
        RESERVED3 = 64,
        RESERVED4 = 65,
        UltimatumCraftingItem = 66,
        RESERVED5 = 67,
        RESERVED6 = 68,
        ExpeditionStorage1 = 69,
        HellscapeModificationInventory1 = 70,
        DONOTUSE6 = 71,
        SentinelDroneInventory1 = 72,
        SentinelStorage1 = 73,
        LakeTabletInventory1 = 74,
        DONOTUSE7 = 75,
        Relics1 = 76,
        RelicStorage1 = 77,
        SanctumSpecialRelic1 = 78,
        RESERVED7 = 79,
        RESERVED8 = 80,
        RESERVED9 = 81,
        CurrentSanctumRun1 = 82,
        CraftPredictionScratch = 83,
        ExpandedMainInventory1 = 84,
        NecropolisStorage1 = 85,
        MavenInvitations = 86,
        KalguurDisenchanting1 = 87,
        KalguurMapping1 = 88,
        MapRelics1 = 89,
        MapRelics2 = 90,
        MapRelics3 = 91,
        RecombinatorInput = 92,
        RecombinatorOutput = 93,
        MemoryLineMaps1 = 94,
        Mercenary1 = 95,
        Mercenary2 = 96,
        Mercenary3 = 97,
        DONOTUSE8 = 98,
        UNUSED1 = 99,
        DONOTUSE9 = 100,
        BrequelStorage1 = 101,
        Ring3 = 102,
        DeepwaterUnchartedMission = 103,
        DeepwaterChartedMissionStorage = 104,
        DeepwaterCraftingInput = 105,
        DeepwaterCraftingOutputStorage = 106,
        MercenaryTemporary = 107,
        LegionCocoonedItems = 108,
        DeepwaterActiveMission = 109,
        AbyssPinnacleExchangeInput = 110,
        AbyssPinnacleExchangeOutput = 111,
        DeepwaterLockerInventory1 = 112,
        DeepwaterExtractionInventory1 = 113,
        DeepwaterCollectionInventory1 = 114,
        Invalid = -1,
    }
}
