using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace ExileCore.PoEMemory.FilesInMemory;
[JsonConverter(typeof(StringEnumConverter))]
public enum StatHandling
{
    NoFunction = 1,
    Negate,
    PerMinuteToPerSecond,
    PerMinuteToPerSecond0dp,
    PerMinuteToPerSecond1dp,
    PerMinuteToPerSecond2dp,
    PerMinuteToPerSecond2dpIfRequired,
    PermyriadPerMinuteToPercentPerSecond,
    DecisecondsToSeconds,
    MillisecondsToSeconds,
    MillisecondsToSeconds0dp,
    MillisecondsToSeconds1dp,
    MillisecondsToSeconds2dp,
    MillisecondsToSeconds2dpIfRequired,
    DivideByOneHundred,
    DivideByOneHundred0dp,
    DivideByOneHundred1dp,
    DivideByOneHundred2dp,
    DivideByOneHundredAndNegate,
    MultiplicativeDamageModifier,
    ModValueToItemClass,
    MultiplicativePermyriadDamageModifier,
    OldLeechPercent,
    OldLeechPermyriad,
    TempestModText,
    SixtyPercentOfValue,
    ThirtyPercentOfValue,
    DivideByTen0dp,
    DivideByTwentyThenDouble0dp,
    DivideByFifteen0dp,
    DivideByTwo0dp,
    MultiplyByEightyThenMsToSeconds0dp,
    TimesTwenty,
    DivideByTwelve,
    DivideBySix,
    PassiveHash,
    IndexToTreeExpansionJewelPassive,
    AfflictionRewardType,
    DisplayIndexableSupport,
    DivideByFive,
    DivideByThree,
    MultiplyByFour,
    MultiplyByFourAndNegate,
    MillisecondsToSecondsHalved,
    DivideByTen1dp,
    DivideByTen1dpIfRequired,
    DivideByOneHundred2dpIfRequired,
    NegateAndDouble,
    Double,
    TimesOnePointFive,
    DivideByFour,
    DivideByFifty,
    MultiplyByTen,
    DivideByOneThousand,
    PlusTwoHundred,
    WeaponTreeUniqueBaseTypeName,
    DisplayIndexableSkill,
    DivideByTwenty,
    LocationUnitsToMetres,
    InvertChance
}